import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.scss'
import { Sidebar } from '@/components/sidebar/sidebar'
import { Topbar } from '@/components/topbar/topbar'
import Providers from '@/components/providers/providers'
import { getServerSession } from 'next-auth'
import { Protected } from '@/components/protected/protected'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers session={session}>
          <Protected>

            <Sidebar />
            <main className="main">
              <Topbar />
              {children}
            </main>

          </Protected>
        </Providers>
      </body>
    </html>
  )
}
